import Header from './Components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from './Components/Footer'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Aditya Shekhar',
//   description: 'Generated by Aditya Shekhar',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Aditya Shekhar - Web Developer & Ethical Hacker</title>
        <meta name="google-site-verification" content="H4gNKtuaXkIyq9TrTcPP8RPZux_YQDeEvVGxi8Cfd6M" />
        <meta name="description" content="Experienced web developer specializing in Laravel, JavaScript, and Python. Currently expanding knowledge in Ethical Hacking. Check out my portfolio for innovative projects."/>
        <meta name="keywords" content="web development, Laravel, JavaScript, Python, Ethical Hacking, portfolio"/>

      </head>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
